//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<bea_Result> bea(Nullable<System.DateTime> date1, Nullable<System.DateTime> date2)
        {
            var date1Parameter = date1.HasValue ?
                new ObjectParameter("date1", date1) :
                new ObjectParameter("date1", typeof(System.DateTime));
    
            var date2Parameter = date2.HasValue ?
                new ObjectParameter("date2", date2) :
                new ObjectParameter("date2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<bea_Result>("bea", date1Parameter, date2Parameter);
        }
    
        public virtual ObjectResult<DataCleaningIndicators_Result> DataCleaningIndicators(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DataCleaningIndicators_Result>("DataCleaningIndicators", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<DataCleaningList_Result> DataCleaningList(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DataCleaningList_Result>("DataCleaningList", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<latitudeLogitudeData_Result> latitudeLogitudeData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<latitudeLogitudeData_Result>("latitudeLogitudeData");
        }
    
        public virtual ObjectResult<OverSelectedCluster_Result> OverSelectedCluster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OverSelectedCluster_Result>("OverSelectedCluster");
        }
    
        public virtual ObjectResult<PCS_Cummulative_Report_Result> PCS_Cummulative_Report(Nullable<System.DateTime> seconddate)
        {
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Cummulative_Report_Result>("PCS_Cummulative_Report", seconddateParameter);
        }
    
        public virtual ObjectResult<PCS_Dashboard_1_Main_Result> PCS_Dashboard_1_Main(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Dashboard_1_Main_Result>("PCS_Dashboard_1_Main", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<PCS_Dashboard_1_Main_Monthly_Result> PCS_Dashboard_1_Main_Monthly()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Dashboard_1_Main_Monthly_Result>("PCS_Dashboard_1_Main_Monthly");
        }
    
        public virtual ObjectResult<PCS_Dashboard_RP_Generation_Result> PCS_Dashboard_RP_Generation(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Dashboard_RP_Generation_Result>("PCS_Dashboard_RP_Generation", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<PCS_Data_Weekly_Report_1_Result> PCS_Data_Weekly_Report_1(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Data_Weekly_Report_1_Result>("PCS_Data_Weekly_Report_1", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<PCS_Data_Weekly_Report_No_OfRecords_Result> PCS_Data_Weekly_Report_No_OfRecords(Nullable<System.DateTime> firstdate, Nullable<System.DateTime> seconddate)
        {
            var firstdateParameter = firstdate.HasValue ?
                new ObjectParameter("firstdate", firstdate) :
                new ObjectParameter("firstdate", typeof(System.DateTime));
    
            var seconddateParameter = seconddate.HasValue ?
                new ObjectParameter("seconddate", seconddate) :
                new ObjectParameter("seconddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_Data_Weekly_Report_No_OfRecords_Result>("PCS_Data_Weekly_Report_No_OfRecords", firstdateParameter, seconddateParameter);
        }
    
        public virtual ObjectResult<PCS_SocialContactCheck_Result> PCS_SocialContactCheck(Nullable<System.DateTime> enddate)
        {
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PCS_SocialContactCheck_Result>("PCS_SocialContactCheck", enddateParameter);
        }
    
        public virtual ObjectResult<ViewByCluster_Result> ViewByCluster(string clusterId)
        {
            var clusterIdParameter = clusterId != null ?
                new ObjectParameter("clusterId", clusterId) :
                new ObjectParameter("clusterId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewByCluster_Result>("ViewByCluster", clusterIdParameter);
        }
    }
}
